services:
    nginx:
        env_file:
            - ./../.env
        container_name: "${APP_NAME:-pzadmin}_nginx"
        build: ./nginx
        ports:
            - "${APP_HTTP:-80}:80"
            - "${APP_HTTPS:-443}:443"
            - "${VITE_REVERB_PORT:-8080}:8080"
            - "${VITE_PORT:-5173}:5173"
            - "${INERTIA_PORT:-13714}:13714"
        networks:
            - backend
        volumes:
            - "${STORAGE_APP}:/var/www/html"
            - "${STORAGE_NGINX}/logs/:/var/log/nginx/"
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/sites-available/:/etc/nginx/sites-available/
            - ./nginx/config/sites-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/config/nginxconfig.io/:/etc/nginx/nginxconfig.io/

    fpm:
        env_file:
            - ./../.env
        container_name: "${APP_NAME:-pzadmin}_fpm"
        build: ./fpm
        networks:
            - backend
        volumes:
            - "${DOCKER_SOCKET}:/var/run/docker.sock"
            - "${STORAGE_APP}:/var/www/html"
            - ./fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf

    php-setup:
        container_name: "${APP_NAME:-pzadmin}_php-setup"
        build: ./php
        networks:
            - backend
        restart: no
        entrypoint: ["bash", "/usr/local/bin/scripts/setup.sh"]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-queue:
        container_name: "${APP_NAME:-pzadmin}_php-queue"
        build: ./php
        networks:
            - backend
        restart: always
        entrypoint: [ "bash", "/usr/local/bin/scripts/laravel_queue.sh" ]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-scheduler:
        container_name: "${APP_NAME:-pzadmin}_php-scheduler"
        build: ./php
        networks:
            - backend
        restart: always
        entrypoint: [ "bash", "/usr/local/bin/scripts/laravel_scheduler.sh" ]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-vite-dev:
        container_name: "${APP_NAME:-pzadmin}_php-vite-dev"
        build: ./php
        networks:
            - backend
        restart: "always"
        entrypoint: [ "bash", "/usr/local/bin/scripts/vite_dev.sh", "-d", "${APP_VITE_DEV}"]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-laravel-reverb:
        container_name: "${APP_NAME:-pzadmin}_php-laravel-reverb"
        build: ./php
        networks:
            - backend
        restart: "always"
        entrypoint: [ "bash", "/usr/local/bin/scripts/laravel_reverb.sh" ]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    zomboid:
        container_name: "${APP_NAME:-pzadmin}_zomboid"
        restart: unless-stopped
        build: ./zomboid
        healthcheck:
            test:
                - CMD-SHELL
                - grep -q '\*\*\* SERVER STARTED \*\*\*\*' /root/Zomboid/server-console.txt
            interval: 3s
            retries: 10
            start_period: 0s
        env_file:
            - ./../.env
        ports:
            - "${ZOMBOID_PORT_1}:16261/udp"
            - "${ZOMBOID_PORT_2}:16262/udp"
            - "${ZOMBOID_STEAM_PORT_1}:8766"
            - "${ZOMBOID_STEAM_PORT_2}:8767"
            - "${ZOMBOID_RCON_PORT}:27015"
        volumes:
            # Server data
            - "${STORAGE_ZOMBOID_DATA}:/root/Zomboid"
            # Workshop mods folder
            - "${STORAGE_ZOMBOID_MODS}:/pz-dedicated/steamapps/workshop"

networks:
    backend:
        driver: bridge
