<?php

declare(strict_types=1);

namespace App\Services\Zomboid;

use App\Jobs\App\Zomboid\Backup\StartBackupJob;
use App\Jobs\App\Zomboid\StartServerJob;
use Illuminate\Support\Facades\Bus;

class ZomboidProxyService extends ZomboidService
{
    public function doStart(): bool
    {
        if ($this->backupService->backupRequired()) {
            Bus::chain([
                new StartBackupJob,
                new StartServerJob,
            ])->dispatch();

            sleep(5);

            return true;
        }

        return parent::doStart(); // TODO: Change the autogenerated stub
    }
}
